@startuml
skinparam ArrowFontStyle plain

actor User
participant ":PharmaTracker" as PharmaTracker
participant "<<class>>\nLoggerSetup" as LoggerSetup
participant ":Ui" as Ui
participant ":Storage" as Storage
participant ":Inventory" as Inventory
participant ":CustomerList" as CustomerList
participant "<<class>>\nParser" as Parser
participant "c:Command" as Command

User -> PharmaTracker : launch app
activate PharmaTracker

PharmaTracker -> LoggerSetup : init()
activate LoggerSetup
LoggerSetup --> PharmaTracker
deactivate LoggerSetup

create Ui
PharmaTracker -> Ui : new Ui()
activate Ui
Ui --> PharmaTracker
deactivate Ui

create Storage
PharmaTracker -> Storage : new Storage()
activate Storage
Storage --> PharmaTracker
deactivate Storage

PharmaTracker -> Storage : load()
activate Storage
create Inventory
Storage -> Inventory : new Inventory()
activate Inventory
Inventory --> Storage
deactivate Inventory
Storage --> PharmaTracker : inventory
deactivate Storage

create CustomerList
PharmaTracker -> CustomerList : new CustomerList()
activate CustomerList
CustomerList --> PharmaTracker
deactivate CustomerList

PharmaTracker -> Ui : printWelcomeMessage()
activate Ui
Ui --> PharmaTracker
deactivate Ui

loop continuous execution loop
    PharmaTracker -> Ui : readCommand()
    activate Ui
    User --> Ui : input string
    Ui --> PharmaTracker : fullCommand
    deactivate Ui

    PharmaTracker -> Parser : parse(fullCommand)
    activate Parser

    create Command
    Parser -> Command : instantiate specific command
    activate Command
    Command --> Parser : c
    deactivate Command

    Parser --> PharmaTracker : c
    deactivate Parser

    PharmaTracker -> Command : execute(inventory, ui, customerList)
    activate Command

    note right of Command
        Execution details depend
        on the specific command.
    end note

    Command --> PharmaTracker
    deactivate Command

    PharmaTracker -> Storage : save(inventory)
    activate Storage
    Storage --> PharmaTracker
    deactivate Storage

    destroy Command
end

deactivate PharmaTracker
@enduml