@startuml
skinparam ArrowFontStyle plain

actor User
participant ":PharmaTracker" as PharmaTracker
participant ":Ui" as Ui
participant "<<class>>\nPharmaTrackerParser" as Parser
participant "c:ViewCustomerCommand" as ViewCustomerCommand
participant "customerList:CustomerList" as CustomerList
participant "customer:Customer" as Customer

User -> PharmaTracker : "view-customer 1"
activate PharmaTracker

PharmaTracker -> Ui : readCommand()
activate Ui
Ui --> PharmaTracker : fullCommand
deactivate Ui

PharmaTracker -> Parser : parse(fullCommand)
activate Parser

alt description is not a valid integer
    Parser -> Parser : throw PharmaTrackerException\n("Invalid format. Usage: view-customer INDEX")
else valid index provided
    create ViewCustomerCommand
    Parser -> ViewCustomerCommand : new ViewCustomerCommand(index)
    activate ViewCustomerCommand
    ViewCustomerCommand --> Parser : c
    deactivate ViewCustomerCommand
end

Parser --> PharmaTracker : c
deactivate Parser

PharmaTracker -> ViewCustomerCommand : execute(inv, ui, customerList)
activate ViewCustomerCommand

ViewCustomerCommand -> CustomerList : size()
activate CustomerList
CustomerList --> ViewCustomerCommand : size
deactivate CustomerList

alt customer list is empty
    ViewCustomerCommand -> Ui : printMessage("No customers registered yet.")
    activate Ui
    Ui --> ViewCustomerCommand
    deactivate Ui
else index is out of range
    ViewCustomerCommand -> Ui : printMessage("Invalid index...")
    activate Ui
    Ui --> ViewCustomerCommand
    deactivate Ui
else valid request
    ViewCustomerCommand -> CustomerList : getCustomer(index - 1)
    activate CustomerList
    CustomerList --> ViewCustomerCommand : customer
    deactivate CustomerList

    ViewCustomerCommand -> Ui : showCustomerDetails(customer)
    activate Ui
    Ui --> ViewCustomerCommand
    deactivate Ui
end

ViewCustomerCommand --> PharmaTracker
deactivate ViewCustomerCommand

deactivate PharmaTracker
@enduml
